# Generated by Django 5.0.14 on 2026-07-04 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('license_no', models.CharField(blank=True, max_length=60, verbose_name='License number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloodbank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('component', models.CharField(choices=[('WHOLE', 'Whole Blood'), ('RBC', 'Red Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets')], max_length=20)),
                ('quantity_ml', models.PositiveIntegerField(default=450)),
                ('collected_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='HemoHubApp.bloodbank')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='TransferAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired')], default='OPEN', max_length=10)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_claimed', to='HemoHubApp.bloodbank')),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='HemoHubApp.bloodbank')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='HemoHubApp.bloodunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
